# Generated by Django 4.0.3 on 2022-03-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identifikationsnummer')),
                ('location', models.CharField(max_length=256, verbose_name='Wohnort')),
                ('p_max', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Maximale Leistung')),
            ],
        ),
    ]