    # Generated by Django 4.0.3 on 2022-03-16 22:53

from django.db import migrations, models

def create_data(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    Client(id=42, location="Meschede", p_max="1337").save()

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]

